# Generated by Django 3.2.7 on 2021-09-06 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='caption',
            field=models.TextField(blank=True, null=True),
        ),
    ]
