# Generated by Django 3.2.7 on 2021-09-06 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark_api', '0002_alter_bookmark_caption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='uses',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='uses',
        ),
        migrations.AddField(
            model_name='bookmark',
            name='categories',
            field=models.ManyToManyField(to='bookmark_api.Category'),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='tags',
            field=models.ManyToManyField(to='bookmark_api.Tag'),
        ),
    ]
